[project]
name = "skylanderstt-gamepad-driver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=1.0.1",
    "evdev>=1.9.2",
    "python-uinput>=1.0.1",
]
